import React from 'react'

const Items = [
    {
        "name":"Crocs",
        "price":"522",
        "image":[1,2,3]
    },
    {
        "name":"sush-yoga-doll",
        "price":"66",
        "image":[1,2,3]
    },
    {
        "name":"robot",
        "price":"66",
        "image":[1,2]
    },
    {
        "name":"unicorn",
        "price":"66",
        "image":[1,2]
    },
    {
        "name":"ring-stacker",
        "price":"66",
        "image":[1,2,3]
    },
    {
        "name":"penguin",
        "price":"66",
        "image":[1,2,3]
    },
    {
        "name":"musketeers",
        "price":"66",
        "image":[1,2,3,4]
    },
    {
        "name":"fabric-balloon",
        "price":"66",
        "image":[1,2]
    },
    {
        "name":"cushion",
        "price":"66",
        "image":[1,2]
    },
    {
        "name":"badal",
        "price":"66",
        "image":[1]
    },
    {
        "name":"crown",
        "price":"66",
        "image":[1]
    },
    {
        "name":"customised-name-bunting",
        "price":"66",
        "image":[1,2]
    },
    {
        "name":"giffy-the-giraffe",
        "price":"66",
        "image":[1,2]
    },
    {
        "name":"hathi",
        "price":"66",
        "image":[1]
    },
    {
        "name":"Rocky-the-rocket",
        "price":"66",
        "image":[1,2]
    },
    {
        "name":"sky-in-a-room",
        "price":"66",
        "image":[1]
    },
    
   
]

export default Items